
# basic image
FROM node:14-alpine

## used to define the working directory of a Docker container
#WORKDIR /USR/APP

# install some dependencies
#COPY ./ ./
RUN npm install

# Default command, run the command npm start.
CMD ["npm", "start"]